export const LASER_MANUFACTURERS = [
  'Coherent',
  'IPG Photonics',
  'TRUMPF',
  'nLIGHT',
  'Lumentum',
  'II-VI Incorporated',
  'Jenoptik',
  'Laserline',
  'Rofin-Sinar',
  'Amada',
  'Bystronic',
  'Prima Power',
  'Mazak',
  'DMG MORI',
  'Haas',
  'Fanuc',
  'Siemens',
  'ABB',
  'KUKA',
  'Universal Robots',
  'Stäubli',
  'Yaskawa',
  'Kawasaki',
  'Nachi',
  'Denso',
  'Epson',
  'Mitsubishi',
  'Panasonic',
  'Omron',
  'Keyence',
  'Cognex',
  'Basler',
  'Teledyne',
  'FLIR',
  'Hamamatsu',
  'Thorlabs',
  'Newport',
  'Edmund Optics',
  'Melles Griot',
  'Spectra-Physics',
  'Quantel',
  'Lumibird',
  'Amplitude',
  'Ekspla',
  'Light Conversion',
  'Photonics Industries',
  'RPMC Lasers',
  'Opto Engine',
  'Altechna',
  'Litron',
  'Continuum',
  'Big Sky',
  'InnoLas',
  'Laser Quantum',
  'Fianium',
  'Toptica',
  'Menlo Systems',
  'NKT Photonics',
  'Fibercore',
  'Corning',
  'OFS',
  'Prysmian',
  'Sumitomo',
  'Fujikura',
  'Furukawa',
  'Yokogawa',
  'Anritsu',
  'Advantest',
  'Tektronix',
  'Keysight',
  'Rohde & Schwarz',
  'Agilent',
  'Bruker',
  'PerkinElmer',
  'Thermo Fisher',
  'Waters',
  'Shimadzu',
  'Hitachi',
  'JEOL',
  'Zeiss',
  'Leica',
  'Olympus',
  'Nikon',
  'Canon',
  'Sony',
  'Samsung',
  'LG',
  'Sharp',
  'Toshiba',
  'Hitachi',
  'Mitsubishi Electric',
  'Fujitsu',
  'NEC',
  'Ricoh',
  'Konica Minolta',
  'Epson',
  'Brother',
  'HP',
  'Dell',
  'Lenovo',
  'ASUS',
  'Acer',
  'MSI',
  'Gigabyte',
  'EVGA',
  'Corsair',
  'Thermaltake',
  'Cooler Master',
  'NZXT',
  'Fractal Design',
  'Phanteks',
  'be quiet!',
  'Noctua',
  'Arctic',
  'Scythe',
  'DeepCool',
  'ID-COOLING',
  'Jonsbo',
  'Silverstone',
  'Lian Li',
  'InWin',
  'BitFenix',
  'NZXT',
  'Phanteks',
  'Fractal Design',
  'be quiet!',
  'Noctua',
  'Arctic',
  'Scythe',
  'DeepCool',
  'ID-COOLING',
  'Jonsbo',
  'Silverstone',
  'Lian Li',
  'InWin',
  'BitFenix'
] as const

export const US_STATES = [
  'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut',
  'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa',
  'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan',
  'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
  'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio',
  'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
  'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia',
  'Wisconsin', 'Wyoming'
] as const

export const JOB_PRIORITIES = ['P0', 'P1', 'P2', 'SCOTT'] as const
export const JOB_STATUSES = ['OPEN', 'BIDDING', 'AWARDED', 'SCHEDULED', 'IN_PROGRESS', 'AWAITING_PARTS', 'COMPLETED', 'CANCELED'] as const
export const JOB_TYPES = ['tech', 'trainer'] as const
