-- MED Equipment Tech V0 - Insert Mock Data Migration
-- This migration inserts mock data from the CSV files in the data directory

-- Note: We cannot insert profiles directly due to foreign key constraints with auth.users
-- Profiles will be created when users sign up through the application
-- This migration focuses on jobs and other data that can be inserted without auth dependencies

-- Insert demo jobs (open tickets) based on mock_open_tickets.csv
INSERT INTO jobs (
    external_id,
    job_type,
    title,
    company_name,
    customer_name,
    model,
    priority,
    status,
    met_date,
    shipping_state,
    shipping_city,
    contact_name,
    contact_phone,
    contact_email,
    instructions_public,
    instructions_private,
    created_at,
    updated_at
) VALUES 
-- Technician Jobs from mock_open_tickets.csv
(
    'OPS-001',
    'tech',
    'VBeam Perfecta PM & Calibration',
    'Beauty MedSpa',
    'Dr. Sarah Williams',
    'VBeam Perfecta',
    'P1',
    'OPEN',
    '2025-08-25',
    'CA',
    'Los Angeles',
    'Dr. Sarah Williams',
    '555-123-4567',
    'dr.williams@beautymedspa.com',
    'PM with dye kit replacement, DI filter change, and full calibration',
    'System showing error codes for dye pump assembly. Requires immediate attention.',
    NOW(),
    NOW()
),
(
    'OPS-002',
    'tech',
    'GentleMax Pro Maintenance',
    'Glow Aesthetics',
    'Dr. Michael Chen',
    'GentleMax Pro',
    'P2',
    'OPEN',
    '2025-08-26',
    'TX',
    'Dallas',
    'Dr. Michael Chen',
    '555-234-5678',
    'dr.chen@glowaesthetics.com',
    'Standard PM with flash lamp replacement, dual filter change, and energy calibration',
    'System needs maintenance code reset after service.',
    NOW(),
    NOW()
),
(
    'OPS-003',
    'tech',
    'M22 IPL System Service',
    'Radiance MedSpa',
    'Dr. Lisa Rodriguez',
    'M22',
    'P1',
    'BIDDING',
    '2025-08-27',
    'NY',
    'Brooklyn',
    'Dr. Lisa Rodriguez',
    '555-345-6789',
    'dr.rodriguez@radiancemedspa.com',
    'PM with DI filter replacement, coolant flush, and IPL calibration',
    'Possible HV relay causing noise. May need replacement.',
    NOW(),
    NOW()
),
(
    'OPS-004',
    'tech',
    'Icon Flash Lamp Replacement',
    'Perfect Skin Center',
    'Dr. David Thompson',
    'Icon',
    'P2',
    'OPEN',
    '2025-08-24',
    'IL',
    'Chicago',
    'Dr. David Thompson',
    '555-456-7890',
    'dr.thompson@perfectskin.com',
    'Flash lamp replacement needed with system calibration',
    'System showing lamp hours exceeded. Warranty service.',
    NOW(),
    NOW()
),
(
    'OPS-005',
    'tech',
    'Sciton Halo Fractional Service',
    'Elite Dermatology',
    'Dr. Jennifer Lee',
    'Sciton Halo',
    'P1',
    'OPEN',
    '2025-08-28',
    'FL',
    'Miami',
    'Dr. Jennifer Lee',
    '555-567-8901',
    'dr.lee@elitedermatology.com',
    'PM with fractional handpiece calibration, DI filter replacement, and energy verification',
    'System needs software update after maintenance.',
    NOW(),
    NOW()
),
-- Trainer Jobs from mock_open_tickets.csv
(
    'OPS-006',
    'trainer',
    'BBL Hero Staff Training',
    'Advanced Aesthetics',
    'Dr. Christopher Brown',
    'BBL Hero',
    'P2',
    'OPEN',
    '2025-08-29',
    'GA',
    'Atlanta',
    'Dr. Christopher Brown',
    '555-678-9012',
    'dr.brown@advancedaesthetics.com',
    'Staff training on BBL Hero system operation and safety protocols',
    'New staff members need comprehensive training on device operation.',
    NOW(),
    NOW()
),
(
    'OPS-007',
    'trainer',
    'Picosure Training Session',
    'Precision MedSpa',
    'Dr. Rachel Green',
    'Picosure',
    'P1',
    'BIDDING',
    '2025-08-30',
    'WA',
    'Seattle',
    'Dr. Rachel Green',
    '555-789-0123',
    'dr.green@precisionmedspa.com',
    'Advanced Picosure training for experienced staff',
    'Staff needs advanced techniques training for new procedures.',
    NOW(),
    NOW()
),
(
    'OPS-008',
    'trainer',
    'Alma Harmony RF Training',
    'Beauty & Beyond',
    'Dr. Ryan Anderson',
    'Alma Harmony',
    'P2',
    'OPEN',
    '2025-08-31',
    'NC',
    'Charlotte',
    'Dr. Ryan Anderson',
    '555-890-1234',
    'dr.anderson@beautyandbeyond.com',
    'RF calibration training and advanced treatment protocols',
    'Staff needs training on new RF protocols and safety measures.',
    NOW(),
    NOW()
),
(
    'OPS-009',
    'trainer',
    'InMode Morpheus Training',
    'Glow Medical Spa',
    'Dr. Amanda Foster',
    'InMode Morpheus',
    'P1',
    'OPEN',
    '2025-09-01',
    'CA',
    'San Francisco',
    'Dr. Amanda Foster',
    '555-111-2222',
    'dr.foster@glowmedicalspa.com',
    'Comprehensive training on Morpheus RF system',
    'New device installation requires full staff training.',
    NOW(),
    NOW()
),
(
    'OPS-010',
    'trainer',
    'BTL Emsella Training Program',
    'Elite Aesthetics',
    'Dr. Jessica Martinez',
    'BTL Emsella',
    'P2',
    'OPEN',
    '2025-09-02',
    'FL',
    'Orlando',
    'Dr. Jessica Martinez',
    '555-222-3333',
    'dr.martinez@eliteaesthetics.com',
    'Emsella chair operation and treatment protocols training',
    'Staff needs training on new pelvic floor treatment protocols.',
    NOW(),
    NOW()
);

-- Create a sample import record
INSERT INTO imports (
    source,
    mapping_json,
    row_count,
    created_at
) VALUES 
(
    'csv',
    '{"technicians": "mock_technicians.csv", "trainers": "mock_trainers.csv", "jobs": "mock_open_tickets.csv"}',
    28,
    NOW()
);

-- Note: Bids, awards, email campaigns, and notifications will be created
-- when users sign up and interact with the platform
-- This ensures data integrity and proper foreign key relationships
